# Generated by Django 4.0.2 on 2022-03-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='contetn',
            new_name='content',
        ),
    ]
